### ISSUE TITLE
Clients: Create New Client screen does not load

### ISSUE THREAD

**Issue by marracuene** [vorburger/www.fineract.dev#2]
Steps to reproduce:
1. Login to [https://wui.fineract.dev/](https://wui.fineract.dev/) with mifos/password
2. Click on Institution -> Clients menu at top-left.
3. Click on "Create Client" button... nothing happens.   But monitoring in Chrome Developer Tools, appears to be a problem communicating with backend:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'developerMessage' of null
TypeError: Cannot read property 'developerMessage' of null
    at ErrorHandlerInterceptor.push../src/app/core/http/error-handler.interceptor.ts.ErrorHandlerInterceptor.handleError
```

**Comment by vorburger** [comment]
@marracuene as per Contact & Support at the bottom of https://www.fineract.dev, this issue tracker for anything specific (and only) this fineract.dev server itself (like when this server is down, or a configuration issue specific to this server such as #1). 

The problem you are showing above however seems to be "just" a bug in https://github.com/openMF/web-app, no? So you could either further investigate and debug it yourself, and if you find a fix contribute a Pull Request to that project. Or you could raise a bug about it on that project's issue tracker, and see if anyone who maintains that UI would like to look into fixing it for you. 

But BTW note that wui.fineract.dev is not automatically updated, watch https://github.com/openMF/web-app/issues/1254 about that. So in theory it's possible that this was already fixed in `openMF/web-app`, and would just need an update on this server. Doing that manually for me is a little bit of a PITA until https://github.com/openMF/web-app/issues/786 is addressed. If you are motivated to see this community demo system update, perhaps you would like to contribute to that issue?

OK for you to close this issue?

**Comment by marracuene** [comment]
@vorburger I did read that Contact & Support section.   It seemed to me that this error had a high likelihood of being caused by another component not being available at runtime (such as a serverless node not warming up in time) rather than a code bug.      The same error does not occur at: https://openmf.github.io/web-app.

Unfortunately at this stage I am only evaluating possible MFI system solutions and do not have the cycles to build an instance and reproduce.

I have now read https://github.com/openMF/web-app/issues/786 and I see what you mean about PITA.

I therefore leave it to your discretion, please close this Issue if you prefer.
