### ISSUE TITLE
mifos account password changed

### ISSUE THREAD

**Issue by vorburger** [vorburger/www.fineract.dev#5]
I got an automated alert (from some Google Cloud Monitoring that I had set up) that the _mifos_ account's password on the Fineract.dev demo server changed.

So you currently actually cannot _login with e.g. `mifos`/`password` (anymore), as per https://www.fineract.dev.

This could be due to an intentional malicious intent by some... **idiot** (sorry), or an honest mistake by someone. It doesn't really matter which one it is - I now must manually reset the `mifos` user's password.

The more interesting question is perhaps how to prevent this from happening again.... couple of thoughts with ideas what we could do here for the general underlying issue - opinions welcome, e.g. from @ptuomola or @davidyaha or anyone else interested:

1. Should we look into introducing a feature in Fineract (core) to have "locked passwords"? Then set that on the `mifos` account. It would likely prevent "accidental" changes, but someone truly malicious could still create ANOTHER admin account on the demo server and then use that one to change the `mifos` user account... so yeah, maybe not.

2. Should we just not have a default `mifos`/`password` on our community demo server at all anymore?! But that would then require some other mechanism to "sign up" to get a personal account on it. Could be interesting. Slightly raises the bar for people to try it though. Perhaps that could be a good thing?

**Comment by davidyaha** [comment]
Hey @vorburger 
I think the 2nd approach is preferable. we have a bit of experience with something like that with the "fineract as a service" we used to have. it is currently down and we don't have the capacity to maintain it but something like that could be both easy to use and "safer". Another feature that could be added to what we've done is a population of demo data for each tenant.
This way, each user that wishes to checkout Fineract would have their own tenant with demo data to play with.

This could a significant effort to get this working but so a quick fix for the meantime would be creating an SQL script that sets `mifos/password` each night with something like a scheduled google function.

**Comment by vorburger** [comment]
> a quick fix for the meantime would be creating an SQL script that sets mifos/password each night with something like a scheduled

Yeah, I'm going to fix this doing something like that, for now. One of these evenings or on a future week-end! 😃 

Re. population of demo data, let's continue that discussion in https://issues.apache.org/jira/browse/FINERACT-1238, if you like.

**Comment by vorburger** [comment]
I've FINALLY gotten around to fixing this (just been busy, see also https://github.com/openMF/fineract-pentaho/issues/25), at least manually one off, for now.

Because there also are frequent `java.lang.OutOfMemoryError`, I've just gone ahead and: 1. took a backup of DB instance, 2. stopped server, 3. deleted `fineract_default` DB (NOT instance), 4. re-created `fineract_default` DB, 5. restarted server.

Keeping this issue open for future automation, as above.

**Comment by ptuomola** [comment]
Great stuff - thanks Michael! Good to see Fineract.dev usable again

Just wondering about the permanent fix:

1. Locking this account so that it’s password cannot be changed will just shift the problem to another account - i.e. the root account that then can be used to “unlock” this account. Unless we want to make it so that the unlocking can only be done at a database level? That would work. 

2. Registering for your own account is something that works well with the demo but I’m not sure if it’s a useful feature for a real core banking solution - you really don’t want to allow people to create their own accounts on a real production banking system…

Would the easiest way just be to write a script that resets the Fineract.dev database to original state once a day / once a week? That’s what the website states anyway.. and would mean that anyone stupid enough to change the password would only stop the use of fineract.dev until the next reset…

Alternatively we can do #1 above in such way that the unlocking can only be done at a database level - that should be pretty straightforward….

Regards
Petri

**Comment by vorburger** [comment]
@ptuomola Thank You for https://github.com/apache/fineract/pull/2001 for https://issues.apache.org/jira/browse/FINERACT-1452.

I've now "activated" this for the demo instance (using `UPDATE m_appuser SET cannot_change_password = true; // WHERE id = 1`).

Problem solved & case closed! Thanks again.
